const sequelize=require('./config')
const {DataTypes}=require('sequelize')
const User=sequelize.define('user',{
    id:{
        type:DataTypes.INTEGER,
        primaryKey:true,
        autoIncrement:true
    },
    Email:{
        type:DataTypes.STRING,
        allowNull:false,
    },
    Gender:{
        type:DataTypes.STRING,
        allowNull:false
    },
    Birthday:{
        type:DataTypes.DATE,
        allowNull:false
    },
    Motto:{
        type:DataTypes.STRING,
        allowNull:true
    },
    NickName:{
        type:DataTypes.STRING,
        allowNull:false
    },
    avatar:{
        type:DataTypes.STRING,
        allowNull:true
    },
    pwd:{
        type:DataTypes.STRING,
        allowNull:false
    },
    admin:{
        type:DataTypes.INET,
        allowNull:false,
        defaultValue:0
    },
    date:{
        type:DataTypes.STRING,
        allowNull:false,
    }
},{
    timestamps:false,
    tableName:'user'
})
module.exports=User